# Get All Products
GET http://localhost:5000/api/menus

###
# Get All Orders
GET http://localhost:5000/api/orders

###
# Get product By ID
GET http://localhost:5000/api/products/1
 
###
# Create menus
POST http://localhost:5000/api/order
 Content-Type: application/json

{
    "username" : "Muammar Rizal",
    "data" : "[{id:1,name:'jange'}]"
}

###
# Update Product
PUT http://localhost:5000/api/products/18
Content-Type: application/json

{
    "name" : "Ubi Lembu",
    "price" : 200
}

###
# Delete product BY ID
delete http://localhost:5000/api/products/16